INSERT INTO nba_teams(team_name) VALUES
 ('Trail Blazers'),
 ('Bobcats'),
 ('Bucks'),
 ('Bulls'),
 ('Cavaliers'),
 ('Celtics'),
 ('Clippers'),
 ('Grizzlies'),
 ('Hawks'),
 ('Heat'),
 ('Jazz'),
 ('Kings'),
 ('Knicks'),
 ('Lakers'),
 ('Magic'),
 ('Mavericks'),
 ('Nets'),
 ('Nuggets'),
 ('Pacers'),
 ('Pelicans'),
 ('Pistons'),
 ('Raptors'),
 ('Rockets'),
 ('76ers'),
 ('Spurs'),
 ('Suns'),
 ('Thunder'),
 ('Timberwolves'),
 ('Warriors'),
 ('Wizards');

INSERT INTO nba_champions(team_name, year) VALUES
  ('Heat', 2012),
  ('Heat', 2013);